const std = @import("std");
const fmap = @import("fontmap.zig");

const GPAlloc = std.heap.GeneralPurposeAllocator(.{});
var gpa = GPAlloc{};

pub fn main() !void {
    const alloc = gpa.allocator();
    const map = try fmap.fontMap(alloc);
    const stdout = std.io.getStdOut().writer();
    var it = map.iterator();
    var pre: []const u8 = "\n\t";
    try stdout.print("//generated by zig DO NOT EDIT MANUALLY\n", .{});
    try stdout.print("export const fontMap = {{", .{});
    while (it.next()) |i| {
        try stdout.print("{s}\"{s}\":\"\\u{{{x}}}\"", .{
            pre,
            i.key_ptr.*,
            i.value_ptr.code,
        });
        pre = ",\n\t";
    }
    try stdout.print("\n}};", .{});
}
